//For ascii & arduino keyboard specific keycodes see:
//http://www.asciitable.com/
//https://www.arduino.cc/en/Reference/KeyboardModifiers

#ifdef M
#undef M
#endif
#define M(n) ((n) & KEYCODE_MASK)

const byte Keymap[LAYERS][ROWS][COLUMNS] = 
{
  {//0 Raised layer
    {
      '`',
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '0',
      M(KEY_DELETE)
    },
    {
      NO_ACTION,
      NO_ACTION,
      NO_ACTION,
      NO_ACTION,
      NO_ACTION,
      NO_ACTION,
      NO_ACTION,
      M(KEY_PAGE_UP),
      M(KEY_HOME),
      M(KEY_UP),
      M(KEY_END),
      NO_ACTION    
    },
    {
      M(KEY_LEFT_SHIFT),
      NO_ACTION,
      NO_ACTION,
      NO_ACTION,
      NO_ACTION,
      NO_ACTION,
      NO_ACTION,
      M(KEY_PAGE_DOWN),
      M(KEY_LEFT),
      M(KEY_DOWN),
      M(KEY_RIGHT), 
      NO_ACTION
    },
    {
      M(KEY_LEFT_CTRL),
      NO_ACTION,
      M(KEY_LEFT_GUI),
      M(KEY_LEFT_ALT),
      NO_ACTION,
      ' ',
      ' ',
      LAYER_RAISE,
      NO_ACTION, 
      NO_ACTION,
      NO_ACTION,
      NO_ACTION
    }
  },
  {//1 Default layer
    {
      M(KEY_ESC),
      'q',
      'w',
      'e',
      'r',
      't',
      'y',
      'u',
      'i',
      'o',
      'p',
      M(KEY_BACKSPACE)
    },
    {
      M(KEY_TAB),
      'a',
      's',
      'd',
      'f',
      'g',
      'h',
      'j',
      'k',
      'l',
      ';',
      M(KEY_ENTER)    
    },
    {
      M(KEY_LEFT_SHIFT),
      'z',
      'x',
      'c',
      'v',
      'b',
      'n',
      'm',
      ',',
      '.',
      '/', 
      '\''
    },
    {
      M(KEY_LEFT_CTRL),
      NO_ACTION,
      M(KEY_LEFT_GUI),
      M(KEY_LEFT_ALT),
      LAYER_LOWER,
      ' ',
      ' ',
      LAYER_RAISE,
      NO_ACTION, 
      NO_ACTION,
      NO_ACTION,
      NO_ACTION
    }
  },
  {//2 Lowered layer
    {
      M(KEY_F1),
      M(KEY_F2),
      M(KEY_F3),
      M(KEY_F4),
      M(KEY_F5),
      M(KEY_F6),
      M(KEY_F7),
      M(KEY_F8),
      M(KEY_F9),
      M(KEY_F10),
      M(KEY_F11),
      M(KEY_F12)
    },
    {
      M(KEY_CAPS_LOCK),
      NO_ACTION,
      NO_ACTION,
      NO_ACTION,
      NO_ACTION,
      NO_ACTION,
      NO_ACTION,
      NO_ACTION,
      NO_ACTION,
      '[',
      ']',
      NO_ACTION 
    },
    {
      NO_ACTION,
      NO_ACTION,
      NO_ACTION,
      NO_ACTION,
      NO_ACTION,
      NO_ACTION,
      NO_ACTION,
      NO_ACTION,
      '-',
      '=',
      NO_ACTION, 
      NO_ACTION
    },
    {
      M(KEY_LEFT_CTRL),
      NO_ACTION,
      M(KEY_LEFT_GUI),
      M(KEY_LEFT_ALT),
      LAYER_LOWER,
      ' ',
      ' ',
      NO_ACTION,
      NO_ACTION, 
      NO_ACTION,
      NO_ACTION,
      NO_ACTION
    }
  }
};
